// @generated
// This file is @generated by prost-build.
/// Every event the 1inch Aqua registries emitted in one block, grouped by kind. Order inside a
/// block is the log ordinal carried on each event.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub shipped: ::prost::alloc::vec::Vec<Shipped>,
    #[prost(message, repeated, tag="2")]
    pub docked: ::prost::alloc::vec::Vec<Docked>,
    #[prost(message, repeated, tag="3")]
    pub pushed: ::prost::alloc::vec::Vec<Pushed>,
    #[prost(message, repeated, tag="4")]
    pub pulled: ::prost::alloc::vec::Vec<Pulled>,
}
/// Where an event happened. Addresses and hashes are lowercase hex with the 0x prefix.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ref {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(message, optional, tag="2")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="3")]
    pub tx_hash: ::prost::alloc::string::String,
    /// the account that sent the transaction: the taker on a settlement
    #[prost(string, tag="4")]
    pub tx_from: ::prost::alloc::string::String,
    /// position of the log in the block
    #[prost(uint32, tag="5")]
    pub log_index: u32,
    /// total order of the log within the block, across transactions
    #[prost(uint64, tag="6")]
    pub ordinal: u64,
    /// the registry that emitted it, canonical or legacy
    #[prost(string, tag="7")]
    pub registry: ::prost::alloc::string::String,
}
/// A maker registered a strategy: the blob is what Aqua hashed, program included.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Shipped {
    #[prost(message, optional, tag="1")]
    pub at: ::core::option::Option<Ref>,
    #[prost(string, tag="2")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub strategy_hash: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub strategy: ::prost::alloc::vec::Vec<u8>,
}
/// A maker revoked a strategy.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Docked {
    #[prost(message, optional, tag="1")]
    pub at: ::core::option::Option<Ref>,
    #[prost(string, tag="2")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub strategy_hash: ::prost::alloc::string::String,
}
/// Tokens moved into a strategy's virtual balance. Amounts are decimal strings in raw units.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pushed {
    #[prost(message, optional, tag="1")]
    pub at: ::core::option::Option<Ref>,
    #[prost(string, tag="2")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub strategy_hash: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
}
/// Tokens moved out of a strategy's virtual balance.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pulled {
    #[prost(message, optional, tag="1")]
    pub at: ::core::option::Option<Ref>,
    #[prost(string, tag="2")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub strategy_hash: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
