[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 700
via_ir = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "swap-vm/=lib/swap-vm/src/",
    "aqua/=lib/aqua/src/",
    "@1inch/aqua/=lib/aqua/",
    "@1inch/solidity-utils/=lib/swap-vm/node_modules/@1inch/solidity-utils/",
    "@openzeppelin/contracts/=lib/swap-vm/node_modules/@openzeppelin/contracts/",
]

[fmt]
single_line_statement_blocks = "multi"
bracket_spacing = true
